### ISSUE TITLE
Image snags...(awesome project though)

### ISSUE THREAD

**Issue by thatman84** [thebezelproject/bezelproject-MAME#1]
What a great project thats been done here.

I am just browsing through and noticed a couple of images that REALLY need replacing/updating

![goldnaxe](https://user-images.githubusercontent.com/26202064/39961187-20ca8c7e-5629-11e8-9279-686219de33a8.png)

![gaxeduel](https://user-images.githubusercontent.com/26202064/39961193-33dc0540-5629-11e8-8cc6-e3227eec1249.png)

**Comment by thebezelproject** [comment]
Updated Golden Axe bezels.
