### ISSUE TITLE
Aspect Ratio G

### ISSUE THREAD

**Issue by Spawk-HS** [thebezelproject/bezelproject-MAME#10]
couple for the G's:

galaxyfg - has that odd double image on left side

gekirido
goindol
grdnstrm

All of the Golden Tee games (except 2K) share a bezel that shows up underneath the frame in the gameplay area.

gwar - also suffers from this.

**Comment by thebezelproject** [comment]
Corrected galaxyfg, gekirido, goindol, and the Golden Tee files. Grdnstrm is the horizontal version of the game, therefore no change is required. I can't find anything wrong with gwar. The bezel surround  is what we used as the default for vertical games.
