### ISSUE TITLE
Transparent zones.

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#13]
I've done a more thorough check and these appear to be the last to be fixed.

Here the list:
[list.txt](https://github.com/thebezelproject/bezelproject-MAME/files/5649012/list.txt)

Here the bezels with marks to know zone with transparent pixels.
[https://drive.google.com/drive/folders/11Ua8V-KqjGPcAVieuPcFgmunyTCi5lzx?usp=sharing](url)

**Comment by thebezelproject** [comment]
The list has been updated. A few showed no changes required, but only 2 or 3.
