### ISSUE TITLE
Last with transparent pixels.

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#16]
dogpatch.png
drivedge.png
evosocc.png
pulsar.png
titlef.png
tkoboxng.png
tmek.png

![titlef](https://user-images.githubusercontent.com/20826760/101334728-8b588f80-3878-11eb-9625-a117cba0e4fe.png)
![tkoboxng](https://user-images.githubusercontent.com/20826760/101334731-8bf12600-3878-11eb-8286-08af59aa48fe.png)
![tmek](https://user-images.githubusercontent.com/20826760/101334732-8bf12600-3878-11eb-94e5-3e8bdbb6077d.png)
![pulsar](https://user-images.githubusercontent.com/20826760/101334723-8b588f80-3878-11eb-9349-46ff393c76cb.png)
![dogpatch](https://user-images.githubusercontent.com/20826760/101334717-88f63580-3878-11eb-90ab-ea2706b2dd7c.png)
![drivedge](https://user-images.githubusercontent.com/20826760/101334720-8a276280-3878-11eb-92ea-93dc76a8cd2d.png)
![evosocc](https://user-images.githubusercontent.com/20826760/101334721-8a276280-3878-11eb-8eb6-0a3cab64b3ee.png)

**Comment by thebezelproject** [comment]
Updated png files.
