### ISSUE TITLE
Some improvemetn on the . PNG file

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#17]
Bells & Whistles (blswhstl.png)
Alien Syndrome (aliensyn.png)
Fire Trap (firetrap.png)
Gyruss (gyruss.png)
Juno First (junofrst.png)
King & Balloon (kingball.png)
ordyne (ordyne.png)
Pooyan (pooyan.png)
Rescue (rescue.png)
Roc'n Rope (rocnrope.png)
Super Bagman (sbagman.png)
Twin Hawk (twinhawk.png)
Wrestle War (wrestwar.png)

Some examples:
![aliensyn](https://user-images.githubusercontent.com/20826760/102007585-bcc6d480-3d2a-11eb-9b77-ee9d3ae1d3a6.png)
![firetrap](https://user-images.githubusercontent.com/20826760/102007597-d700b280-3d2a-11eb-95e7-3ceca856f282.png)
![gyruss](https://user-images.githubusercontent.com/20826760/102007622-f13a9080-3d2a-11eb-9221-b7f4116c1841.png)
![wrestwar](https://user-images.githubusercontent.com/20826760/102007631-0b746e80-3d2b-11eb-914f-bc31045a2dc3.png)
![blswhstl](https://user-images.githubusercontent.com/20826760/102007648-2f37b480-3d2b-11eb-8543-f6b75f9d5cdf.png)
![pooyan](https://user-images.githubusercontent.com/20826760/102007660-5098a080-3d2b-11eb-94cd-0746f3ec943b.png)
![rocnrope](https://user-images.githubusercontent.com/20826760/102007672-65753400-3d2b-11eb-9c4e-d3bfd03984fe.png)
![sbagman](https://user-images.githubusercontent.com/20826760/102007690-80e03f00-3d2b-11eb-9665-6a006de60183.png)
![rescue](https://user-images.githubusercontent.com/20826760/102007562-7bcec000-3d2a-11eb-8645-34d15ab064cb.png)

**Comment by thebezelproject** [comment]
Thanks. Updated.
