### ISSUE TITLE
Name set error

### ISSUE THREAD

**Issue by mentat51** [thebezelproject/bezelproject-MAME#19]
Trying to use it with mame (218).
But found some errors : 
1945iii [no corresponding set in mame, maybe 1945kiii (exit in bezel project) or s1945iii]
appe10 [no corresponding set, propably apple10]

Best regards

**Comment by thebezelproject** [comment]
Those are not errors. The bezels were created to match a now older version of MAME which supported those names. As MAME, and other system databases are updated/changed, you will have to rename files to support whatever set you have. Sorry, but there is no one version that will not receive changes by the MAME team.
