### ISSUE TITLE
Zip file is invalid error

### ISSUE THREAD

**Issue by plduganaman** [thebezelproject/bezelproject-MAME#23]
When I try to unzip the file using 7zip I get the error "unexpected end of data"
Also Data error : bezelproject-MAME-master\retroarch\overlay\ArcadeBezels\herbiedk.png

**Comment by thebezelproject** [comment]
Not sure what to say, both the Themed and System Art MAME repo files install fine here. Manually downloading and extracting the zip files for both also work fine.

Make sure you have plenty of space in the filesystem/drive you are downloading to. These repos are quite large, plus you will need double the space for the temporary extraction files.

**Comment by plduganaman** [comment]
After retrying I noticed that downloading sometimes stops before the entire file is complete. I've been using Firefox and will try some other method to download.
