### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#3]
Some overlays contain transparent / translucent pixels outside the desired area.
![spnchout_bezel-16-9(cus) - 3_yellow](https://user-images.githubusercontent.com/20826760/74596729-8f9a8e80-5053-11ea-87ce-9d6976679804.png)

**Comment by toniosj** [comment]
List wrong overlays.

1943kai
1on1gov
40love
actionhw
afighter
alien3
armora
astrob
bankp
bsktball
btoads
carnevil
carnival
ccastles
checkman
chiller
columnsn
commando
coolridr
cyclwarr
daikaiju
dangerz
dariusg
dbzvrvs
ddungeon
defender
docastle
dragrace
enforce
exprraid
flamegun
frogger
g13knd
ga2
gmissile
gpilots
gslgr94u
gslugrsj
gundhara
hal21
hangon
harddunk
hardhat
hattrick
helifire
histryma
hotchase
invaders
jcross
kazan
kengo
killcom
knckhead
koroleva
kov7sprt
kroozr
kungfum
kurikint
kyukaidk
kyustrkr
mace
mach3
madgear
magicbub
majtitl2
mangchi
maniacsq
markham
mars
masterw
msword
mvsc
narc
nbbatman
nemo
nibbler
nstocker
olibochu
pacland
pang3
pdrift
polepos2
quantum
quarterb
radrad
rallyx
rastan
rchase
route16
rthun2
spnchout
sstriker
stmblade
triplep
vf
vr
wargods

**Comment by toniosj** [comment]
https://drive.google.com/file/d/1W6gCNrLcqFdgFs_CYZsjWSjiAhEt84W4/view?usp=sharing

Here you can see the specific areas that have pixels outside the desired area.

**Comment by thebezelproject** [comment]
I have updated 88 files from your list. The remaining are not from this project, so you will either have to fix them yourself, or if you know the author, contact them with a suggested alteration. Here are the files I could not fix.
columnsn.png
coolridr.png
mace.png
pdrift.png
polepos2.png
rchase.png
vf.png
vr.png
wargods.png

**Comment by toniosj** [comment]
I would remove those overlays from the pack, I think they don't follow the design of the rest of the overlays.

**Comment by toniosj** [comment]
I have given a second and definitive review, and I have found the following incorrect overlays.

25pacman.png
4dwarrio.png
4in1boot.png
alienar.png
aliencha.png
btoads.png
dbz.png
dday.png
dorunrun.png
dowild.png
dragngun.png
enduror.png
eprom.png
espial.png
eto.png
fround.png
gaia.png
gigandes.png
gunmast.png
hedpanic.png
hoops96.png
hopmappy.png
horizon.png
jumpkids.png
kamenrid.png
karatblz.png
kbash2.png
kidniki.png
killbldp.png
kncljoe.png
kov2p.png
kovshp.png
ksayakyu.png


Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1mhC0wYC2_XaXTRzWZyFkvDjnH979CLaW/view?usp=sharing

**Comment by thebezelproject** [comment]
Thanks. I have updated those files.

**Comment by toniosj** [comment]
Checking again, I have detected that these are still to be corrected. They all have the right margin wrong, btoads included.

btoads
kickoff
kickboy
hardhead
hardhea2
dunkshot
karnovr
alpham2
gururin
joyjoy

![btoads](https://user-images.githubusercontent.com/20826760/75080997-029d7c80-550e-11ea-9875-da020a15b827.png)
![kickoff](https://user-images.githubusercontent.com/20826760/75081000-03cea980-550e-11ea-87ea-64a23e72f49a.png)
![kickboy](https://user-images.githubusercontent.com/20826760/75081001-03cea980-550e-11ea-8acb-0acba87facd6.png)
![hardhead](https://user-images.githubusercontent.com/20826760/75081002-03cea980-550e-11ea-8362-8deed8ab4726.png)
![hardhea2](https://user-images.githubusercontent.com/20826760/75081003-04674000-550e-11ea-9bf3-28884a559168.png)
![dunkshot](https://user-images.githubusercontent.com/20826760/75081007-04674000-550e-11ea-9fd9-c8192e719fa0.png)
![karnovr](https://user-images.githubusercontent.com/20826760/75081010-05986d00-550e-11ea-9edb-07ba36d84d4b.png)
![alpham2](https://user-images.githubusercontent.com/20826760/75081011-06310380-550e-11ea-944d-f58d0c3c8939.png)
![gururin](https://user-images.githubusercontent.com/20826760/75081013-06c99a00-550e-11ea-9b27-2cb0bb27583b.png)
![joyjoy](https://user-images.githubusercontent.com/20826760/75081015-07623080-550e-11ea-9c4d-d991b1069fa7.png)

**Comment by thebezelproject** [comment]
Updated!

**Comment by toniosj** [comment]
I do not see the updated files. You may not have committed?

**Comment by thebezelproject** [comment]
Had internet connection issues. Changes should be there now.

**Comment by toniosj** [comment]
Great! I'll test them.

**Comment by toniosj** [comment]
All fixed! Great job! Thanks!
