### ISSUE TITLE
Bezels for vertical monitors

### ISSUE THREAD

**Issue by maziac** [thebezelproject/bezelproject-MAME#4]
Hi,
thanks for this collection. It‘s very comprehensive.

But there is a problem for me.
I‘m using a vertical monitor, but all the bezels are cut off on top and bottom.
So, on a vertical monitor there is just empty space.

I guess the original bezel pictures are complete (top and bottom).
Is there a possibility to get the originals?

(I wouldn‘t need all of them! just about 10)

**Comment by thebezelproject** [comment]
Sorry, the bezels were created for a 1080p horizontal monitor. No 'originals' exist that have more coverage top or bottom. Bezels for vertical games do exist in the pack, but again, they were created for a horizontal monitor with more of the bezel showing on the left and right.
