### ISSUE TITLE
Transparent zones.

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#7]
Transparent areas left and up in a almost all bezels.

Example: 3wonders.png

![transparent-zones](https://user-images.githubusercontent.com/20826760/79897765-796dcd80-840a-11ea-86ba-d87b462bee8f.png)

**Comment by thebezelproject** [comment]
The source files aren't available, so I can't address those easily, nor do I have the time to recreate these from scratch. I have been asked how having a very thin semi-transparent border on some of these affects playing the game?

**Comment by toniosj** [comment]
I am correcting those that I am detecting.
![3stooges](https://user-images.githubusercontent.com/20826760/100555571-a46fa800-329c-11eb-8ad8-870bab850598.png)
![mwalk](https://user-images.githubusercontent.com/20826760/100555572-a5083e80-329c-11eb-9fba-2dcd9ae43a34.png)
![3wonders](https://user-images.githubusercontent.com/20826760/100555575-a6396b80-329c-11eb-82fd-64f9ba107e99.png)

**Comment by thebezelproject** [comment]
I have updated 3stooges and mwalk, but can't find any obvious transparent pixels for 3wonders.

**Comment by toniosj** [comment]
Sorry, your 3wonders is ok.

**Comment by toniosj** [comment]
With a software I have checked and detected all the overlays that have transparent pixels outside the screen area. I have a complete list. There are 230 overlays with transparent pixels. If I pass them on to you, could they be corrected? Thank you very much for your work.

**Comment by thebezelproject** [comment]
Possibly, and eventually. Since the existing bezels are still usable in their current state, and most users would never know any transparent pixels exist, priority for updating them would be low priority, at least and until other bezel packs were finished. Please provide the list and I'll add it to the work queue.

**Comment by toniosj** [comment]
Here the list: 
[list.txt](https://github.com/thebezelproject/bezelproject-MAME/files/5623117/list.txt)

Here the bezels with marks to know zone with transparent pixels.
https://drive.google.com/drive/folders/1f9Z-K3LNAkf1o6IkXjttFqYYoiDL5_uR?usp=sharing

**Comment by thebezelproject** [comment]
I was able to automate updating the files in your list, so updated png files are ready in the repo.
