### ISSUE TITLE
Fatal Fury2/3 1440p ?

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MAME#9]
Does it correct that resolution for those games?

2560x1440

**Comment by Spawk-HS** [comment]
1920/1080 = 1.777777
2560/1440 = 1.777777

So at least they should scale properly... or am I not understanding what you mean?

**Comment by toniosj** [comment]
The rest of .png have a resolution of 1920x1080. I thought it would be a mistake if they had a different resolution.

**Comment by thebezelproject** [comment]
Resolution shouldn't matter. Config files specify full screen which should autoscale to max extents.

As far as using 1080p, the default template is 1080p, but as long as the aspect ratio is correct, final resolution should not matter.

**Comment by toniosj** [comment]
OK perfect. Thanks for the clarification. I close it.
